import crypto from "node:crypto";
import { resolveMergedAccountConfig } from "openclaw/plugin-sdk/account-resolution";
import { tryReadSecretFileSync } from "openclaw/plugin-sdk/core";
import {
  createAccountListHelpers,
  DEFAULT_ACCOUNT_ID,
  normalizeAccountId,
  resolveAccountWithDefaultFallback,
} from "../runtime-api.js";
import { normalizeResolvedSecretInputString } from "./secret-input.js";
import type { CoreConfig, GoChatAccountConfig, GoChatMode } from "./types.js";
import { DEFAULT_LOCAL_PORT, DEFAULT_LOCAL_HOST, DEFAULT_RELAY_WS_URL } from "./types.js";

function isTruthyEnvValue(value?: string): boolean {
  const normalized = (value ?? "").trim().toLowerCase();
  return normalized === "true" || normalized === "1" || normalized === "yes" || normalized === "on";
}

const debugAccounts = (...args: unknown[]) => {
  if (isTruthyEnvValue(process.env.OPENCLAW_DEBUG_GOCHAT_ACCOUNTS)) {
    console.warn("[gochat:accounts]", ...args);
  }
};

export type ResolvedGoChatAccount = {
  accountId: string;
  enabled: boolean;
  name?: string;
  mode: GoChatMode;
  secret: string;
  secretSource: "env" | "secretFile" | "config" | "auto" | "none";
  directPort: number;
  directHost: string;
  relayPlatformUrl: string;
  channelId: string;
  config: GoChatAccountConfig;
};

let autoGeneratedSecret: string | null = null;

function getOrCreateAutoSecret(): string {
  if (autoGeneratedSecret) return autoGeneratedSecret;
  autoGeneratedSecret = crypto.randomUUID().replace(/-/g, "") + crypto.randomUUID().replace(/-/g, "").slice(0, 16);
  return autoGeneratedSecret;
}

const {
  listAccountIds: listGoChatAccountIdsInternal,
  resolveDefaultAccountId: resolveDefaultGoChatAccountId,
} = createAccountListHelpers("gochat", {
  normalizeAccountId,
});
export { resolveDefaultGoChatAccountId };

export function listGoChatAccountIds(cfg: CoreConfig): string[] {
  const ids = listGoChatAccountIdsInternal(cfg);
  debugAccounts("listGoChatAccountIds", ids);
  return ids;
}

function normalizeGoChatMode(raw: string | undefined): GoChatMode {
  if (!raw) return "relay";
  const lower = raw.toLowerCase().trim();
  if (lower === "local" || lower === "direct") return "local";
  if (lower === "relay" || lower === "relay-ws") return "relay";
  return "relay";
}

function mergeGoChatAccountConfig(
  cfg: CoreConfig,
  accountId: string,
): GoChatAccountConfig {
  const merged = resolveMergedAccountConfig<GoChatAccountConfig>({
    channelConfig: cfg.channels?.gochat as GoChatAccountConfig | undefined,
    accounts: cfg.channels?.gochat?.accounts as
      | Record<string, Partial<GoChatAccountConfig>>
      | undefined,
    accountId,
    omitKeys: ["defaultAccount"],
    normalizeAccountId,
  });

  if (typeof merged.blockStreaming !== "boolean") {
    merged.blockStreaming = true;
  }

  return merged;
}

function resolveGoChatSecret(
  cfg: CoreConfig,
  opts: { accountId?: string; mode: GoChatMode },
): { secret: string; source: ResolvedGoChatAccount["secretSource"] } {
  const merged = mergeGoChatAccountConfig(cfg, opts.accountId ?? DEFAULT_ACCOUNT_ID);

  const envSecret = process.env.GOCHAT_WEBHOOK_SECRET?.trim();
  if (envSecret && (!opts.accountId || opts.accountId === DEFAULT_ACCOUNT_ID)) {
    return { secret: envSecret, source: "env" };
  }

  if (merged.webhookSecretFile) {
    const fileSecret = tryReadSecretFileSync(
      merged.webhookSecretFile,
      "GoChat webhook secret file",
      { rejectSymlink: true },
    );
    if (fileSecret) {
      return { secret: fileSecret, source: "secretFile" };
    }
  }

  const inlineSecret = normalizeResolvedSecretInputString({
    value: merged.webhookSecret,
    path: `channels.gochat.accounts.${opts.accountId ?? DEFAULT_ACCOUNT_ID}.webhookSecret`,
  });
  if (inlineSecret) {
    return { secret: inlineSecret, source: "config" };
  }

  if (opts.mode === "local") {
    return { secret: getOrCreateAutoSecret(), source: "auto" };
  }

  return { secret: "", source: "none" };
}

export function resolveGoChatAccount(params: {
  cfg: CoreConfig;
  accountId?: string | null;
}): ResolvedGoChatAccount {
  const baseEnabled = params.cfg.channels?.gochat?.enabled !== false;

  const resolve = (accountId: string) => {
    const merged = mergeGoChatAccountConfig(params.cfg, accountId);
    const accountEnabled = merged.enabled !== false;
    const enabled = baseEnabled && accountEnabled;
    const mode = normalizeGoChatMode(merged.mode);
    const secretResolution = resolveGoChatSecret(params.cfg, { accountId, mode });
    const directPort = merged.directPort ?? DEFAULT_LOCAL_PORT;
    const directHost = merged.directHost ?? DEFAULT_LOCAL_HOST;
    const relayPlatformUrl = merged.relayPlatformUrl?.trim()?.replace(/\/+$/, "") || DEFAULT_RELAY_WS_URL;
    const channelId = merged.channelId?.trim() ?? "";

    debugAccounts("resolve", {
      accountId,
      enabled,
      mode,
      secretSource: secretResolution.source,
    });

    const resolved = {
      accountId,
      enabled,
      name: merged.name?.trim() || undefined,
      mode,
      secret: secretResolution.secret,
      secretSource: secretResolution.source,
      directPort,
      directHost,
      relayPlatformUrl,
      channelId,
      config: merged,
    } satisfies ResolvedGoChatAccount;

    console.log(
      `[gochat:config] accountId=${accountId} mode=${mode} enabled=${enabled}` +
      ` secretSource=${secretResolution.source}` +
      (mode === "local" ? ` port=${directPort} host=${directHost}` : "") +
      (mode === "relay" ? ` relayUrl=${relayPlatformUrl} channelId=${channelId || "(pending)"}` : "") +
      ` dmPolicy=${merged.dmPolicy ?? "open"}` +
      ` blockStreaming=${merged.blockStreaming !== false}`,
    );

    return resolved;
  };

  return resolveAccountWithDefaultFallback({
    accountId: params.accountId,
    normalizeAccountId,
    resolvePrimary: resolve,
    hasCredential: (account) => account.secretSource !== "none",
    resolveDefaultAccountId: () => resolveDefaultGoChatAccountId(params.cfg),
  });
}
